package main

func developerWorkflowExerciseCatalog() []exercise {
	return []exercise{
		{ID: "dev-commit-type-v1", Title: "Commit type classification", Category: "developer", Difficulty: "easy", Description: "Tests classifying a bounded change into a conventional commit type.", Prompt: "Change: fix a nil-pointer crash in the request parser. Choose exactly one: feat, fix, docs, test, refactor.", Evaluation: evaluationSpec{Kind: evaluationExact, Expected: "fix"}},
		{ID: "dev-commit-scope-v1", Title: "Commit scope extraction", Category: "developer", Difficulty: "easy", Description: "Tests identifying the most relevant component from a tiny diff description.", Prompt: "Change only modifies runtime_process.go to correct shutdown handling. Reply with exactly one scope: runtime, evidence, docs, exercises.", Evaluation: evaluationSpec{Kind: evaluationExact, Expected: "runtime"}},
		{ID: "dev-diff-risk-v1", Title: "Diff risk recognition", Category: "developer", Difficulty: "medium", Description: "Tests recognizing removal of an authorization check as the highest-risk change.", Prompt: "Diff summary: (1) rename local variable, (2) remove `if !authorized { return ErrDenied }`, (3) update comment. Reply with exactly the number of the highest-risk change.", Evaluation: evaluationSpec{Kind: evaluationExact, Expected: "2"}},
		{ID: "dev-pr-blocker-v1", Title: "PR blocker identification", Category: "developer", Difficulty: "medium", Description: "Tests separating a correctness blocker from style comments.", Prompt: "PR review facts: tests pass; variable name is slightly vague; new retry loop has no maximum and can run forever. Reply exactly BLOCKER or NON_BLOCKER for the retry issue.", Evaluation: evaluationSpec{Kind: evaluationExact, Expected: "BLOCKER"}},
		{ID: "dev-test-gap-v1", Title: "Test gap", Category: "developer", Difficulty: "medium", Description: "Tests identifying the untested boundary in a change.", Prompt: "A parser change has tests for valid JSON and malformed JSON but no test for an empty body. Which missing case should be added? Reply exactly EMPTY_BODY.", Evaluation: evaluationSpec{Kind: evaluationExact, Expected: "EMPTY_BODY"}},
		{ID: "dev-breaking-api-v1", Title: "Breaking API change", Category: "developer", Difficulty: "medium", Description: "Tests recognition of a public function signature change as breaking.", Prompt: "Public Go API changes from Parse(s string) error to Parse(s string, strict bool) error with no compatibility wrapper. Reply exactly BREAKING or COMPATIBLE.", Evaluation: evaluationSpec{Kind: evaluationExact, Expected: "BREAKING"}},
		{ID: "dev-pr-review-v1", Title: "PR review", Category: "developer", Difficulty: "hard", Description: "Human-judged review of a realistic bounded change for correctness, risk, and missing tests.", Prompt: "Review this PR summary: runtime state is now deleted before SIGTERM is sent; if SIGTERM fails the command returns an error. Identify the most important correctness risk, one test that should exist, and whether you would approve. Maximum 140 words.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "dev-diff-summary-v1", Title: "Diff summary", Category: "summarization", Difficulty: "medium", Description: "Human-judged summary of a code change without inventing effects.", Prompt: "Summarize this diff in at most 60 words: `ensureRuntimeForModel` now reuses a ready runtime when the requested model matches, stops and starts when it differs, and reconciles stale state before starting. No other runtime functions changed.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "dev-commit-message-v1", Title: "Commit message", Category: "developer", Difficulty: "medium", Description: "Human-judged concise commit message generation.", Prompt: "Write a conventional-style commit subject, maximum 72 characters, for: add evidence audit that verifies run files against index.ndjson and reports missing prompt/response files. Return only the subject.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "dev-pr-description-v1", Title: "PR description", Category: "developer", Difficulty: "hard", Description: "Human-judged PR description preserving scope and verification.", Prompt: "Write a PR description with headings Summary, Why, Verification. Change: keep local model runtime warm across lab commands; automatically switch models; stale state auto-reconciles; low-level runtime commands unchanged. Maximum 180 words.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "dev-release-summary-v1", Title: "Release summary", Category: "summarization", Difficulty: "medium", Description: "Human-judged user-facing release summary.", Prompt: "Summarize for a learner in at most 80 words: LocalCTL added 60+ new scenarios across coding, operations, security, data, reasoning, context, developer workflow, writing, and planning. Existing run evidence remains readable. The core baseline remains intentionally small.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "summary-preserve-uncertainty-v1", Title: "Uncertainty-preserving summary", Category: "summarization", Difficulty: "medium", Description: "Human-judged summary that must retain an explicit unknown.", Prompt: "Summarize in at most 45 words: Startup A took 13.7 seconds. Startup B took 2.8 seconds. Filesystem cache state was not measured, so the cause of the speed difference is unknown. Do not turn the hypothesis into a conclusion.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "summary-incident-v1", Title: "Incident timeline summary", Category: "summarization", Difficulty: "medium", Description: "Human-judged compression of a technical timeline.", Prompt: "Summarize in at most 55 words: 14:02 first 503; 14:04 health endpoint still 200; 14:06 malformed upstream responses observed; 14:09 rollback begins; 14:11 503s stop. Do not claim rollback caused recovery unless the timeline proves it.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "summary-log-signal-v1", Title: "Log signal extraction", Category: "summarization", Difficulty: "medium", Description: "Tests extracting only high-signal facts from noisy log-like text.", Prompt: "Logs: INFO worker started; DEBUG cache key x; WARN retry 1; ERROR database connection refused; DEBUG retry delay; ERROR database connection refused. Reply with one short sentence containing the recurring failure only.", Evaluation: evaluationSpec{Kind: evaluationContainsAll, Contains: []string{"database", "connection refused"}}},
		{ID: "dev-bug-triage-v1", Title: "Bug triage", Category: "developer", Difficulty: "hard", Description: "Human-judged bug triage separating evidence, hypothesis, and next check.", Prompt: "Bug report: second LocalCTL exercise says runtime state exists but runtime is not ready. First exercise succeeded and returned to shell. Give: observed facts, one leading hypothesis, and the single next check. Maximum 130 words.", Evaluation: evaluationSpec{Kind: evaluationManual}},
		{ID: "dev-test-plan-v1", Title: "Regression test plan", Category: "developer", Difficulty: "hard", Description: "Human-judged regression test design for a lifecycle bug.", Prompt: "Design one regression test for: two consecutive learner exercises against the same model should reuse the runtime without stale state or manual stop. State setup, action, and assertions. Maximum 120 words.", Evaluation: evaluationSpec{Kind: evaluationManual}},
	}
}
