package main

func baselineExerciseCatalog() []exercise {
	return []exercise{
		{
			ID:          "exact-output-v1",
			Title:       "Exact output discipline",
			Category:    "instruction",
			Difficulty:  "easy",
			Description: "Tests whether the model can follow a tiny exact-output contract without adding commentary.",
			Prompt:      "Reply with exactly LOCALCTL_OK and nothing else.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "LOCALCTL_OK"},
		},
		{
			ID:          "lowercase-only-v1",
			Title:       "Format restriction",
			Category:    "instruction",
			Difficulty:  "easy",
			Description: "Tests compliance with a simple formatting constraint.",
			Prompt:      "Reply with exactly three lowercase words separated by single spaces: local models work",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "local models work"},
		},
		{
			ID:          "json-object-v1",
			Title:       "Exact JSON object",
			Category:    "structured",
			Difficulty:  "easy",
			Description: "Tests valid JSON generation and exact key/value compliance.",
			Prompt:      "Return only valid JSON representing an object with status set to ok and count set to 3. No markdown fence and no explanation.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationJSONExact, ExpectedJSON: `{"status":"ok","count":3}`},
		},
		{
			ID:          "json-extraction-v1",
			Title:       "Structured extraction",
			Category:    "structured",
			Difficulty:  "easy",
			Description: "Tests whether facts can be extracted into a strict JSON shape.",
			Prompt:      "Text: Ada joined the Atlas team in 2024 and owns the compiler project. Return only JSON with exactly these keys: name, team, year, project.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationJSONExact, ExpectedJSON: `{"name":"Ada","team":"Atlas","year":2024,"project":"compiler"}`},
		},
		{
			ID:          "json-array-sort-v1",
			Title:       "JSON ordering",
			Category:    "structured",
			Difficulty:  "easy",
			Description: "Tests reasoning plus strict JSON array output.",
			Prompt:      "Sort these integers ascending and return only the JSON array: 9, 2, 7, 2, 5.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationJSONExact, ExpectedJSON: `[2,2,5,7,9]`},
		},
		{
			ID:          "go-defer-order-v1",
			Title:       "Go defer execution order",
			Category:    "coding",
			Difficulty:  "easy",
			Description: "Tests basic Go execution reasoning rather than code generation.",
			Prompt:      "Consider this Go function:\n\nfunc f() {\n    defer fmt.Println(\"first\")\n    defer fmt.Println(\"second\")\n}\n\nReply with exactly the two output lines in order and nothing else.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "second\nfirst"},
		},
		{
			ID:          "go-slice-alias-v1",
			Title:       "Go slice aliasing",
			Category:    "coding",
			Difficulty:  "medium",
			Description: "Tests understanding of shared backing arrays.",
			Prompt:      "What does this Go program print? Reply with only the number.\n\na := []int{1, 2, 3}\nb := a[:2]\nb[0] = 99\nfmt.Println(a[0])",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "99"},
		},
		{
			ID:          "go-map-lookup-v1",
			Title:       "Go map comma-ok",
			Category:    "coding",
			Difficulty:  "easy",
			Description: "Tests Go zero-value and comma-ok semantics.",
			Prompt:      "What does this print? Reply exactly as the two values appear.\n\nm := map[string]int{\"a\": 1}\nv, ok := m[\"missing\"]\nfmt.Println(v, ok)",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "0 false"},
		},
		{
			ID:          "go-unused-variable-v1",
			Title:       "Go compile diagnosis",
			Category:    "coding",
			Difficulty:  "easy",
			Description: "Tests recognition of a common compile-time failure.",
			Prompt:      "This Go function does not compile:\n\nfunc f() {\n    value := 42\n}\n\nState the compiler problem in one short sentence. Do not propose unrelated changes.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationContainsAll, Contains: []string{"value", "not used"}},
		},
		{
			ID:          "go-channel-deadlock-v1",
			Title:       "Go channel deadlock",
			Category:    "coding",
			Difficulty:  "medium",
			Description: "Tests whether the model identifies a simple unbuffered-channel deadlock.",
			Prompt:      "Consider this Go program:\n\nch := make(chan int)\nch <- 1\nfmt.Println(<-ch)\n\nAssume these statements run in the same goroutine and no other goroutines exist. Reply with exactly one word describing the outcome.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "deadlock"},
		},
		{
			ID:          "go-json-tag-v1",
			Title:       "Go JSON tag repair",
			Category:    "coding",
			Difficulty:  "easy",
			Description: "Tests a narrow source-code correction with an exact contract.",
			Prompt:      "A Go struct field is named MaxTokens and must encode as max_tokens. Reply with only the complete Go struct tag, including backticks.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "`json:\"max_tokens\"`"},
		},
		{
			ID:          "go-review-pid-race-v1",
			Title:       "Go process identity review",
			Category:    "coding",
			Difficulty:  "hard",
			Description: "Human-judged review task based on a real systems failure mode: PID identity can change between verification and signaling.",
			Prompt:      "Review this process-control sequence for the single most important race or safety issue:\n\n1. Read a PID from a state file.\n2. Signal PID 0 to check it exists.\n3. Run ps and verify the command line matches the expected executable and model path.\n4. Send SIGTERM to that PID.\n\nIdentify the strongest real safety risk and explain why it matters. Do not invent missing cleanup logic.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
		{
			ID:          "go-refactor-boundary-v1",
			Title:       "Go boundary refactor",
			Category:    "coding",
			Difficulty:  "hard",
			Description: "Human-judged design exercise testing whether the model can preserve process/HTTP responsibility boundaries.",
			Prompt:      "A Go CLI currently has main() calling os.Exit(run(...)). run() dispatches commands. runtimeStatus() performs HTTP health checks. Suggest one small refactor that improves testability without introducing a framework or changing those responsibility boundaries. Explain the tradeoff in at most 150 words.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
		{
			ID:          "shell-pipeline-v1",
			Title:       "Shell pipeline reasoning",
			Category:    "coding",
			Difficulty:  "easy",
			Description: "Tests basic Unix pipeline behavior.",
			Prompt:      "What is the output of this command? Reply with only the output line.\n\nprintf 'alpha\\nbeta\\ngamma\\n' | grep '^b'",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "beta"},
		},
		{
			ID:          "sql-filter-v1",
			Title:       "SQL bounded query",
			Category:    "coding",
			Difficulty:  "medium",
			Description: "Human-judged query generation with explicit constraints.",
			Prompt:      "Table users has columns id, email, active, created_at. Write one SQL SELECT that returns id and email for active users created on or after 2026-01-01, newest first. Return SQL only.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
		{
			ID:          "arithmetic-rate-v1",
			Title:       "Multi-step arithmetic",
			Category:    "reasoning",
			Difficulty:  "easy",
			Description: "Tests a small deterministic word problem.",
			Prompt:      "A local model generates 12 tokens per second for 3 seconds and then 8 tokens per second for 5 seconds. How many tokens were generated total? Reply with only the integer.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "76"},
		},
		{
			ID:          "constraint-elimination-v1",
			Title:       "Constraint elimination",
			Category:    "reasoning",
			Difficulty:  "medium",
			Description: "Tests deterministic eligibility reasoning similar to future model selection problems.",
			Prompt:      "Candidate A has context 4096 and memory 5 GB. Candidate B has context 16384 and memory 9 GB. Requirement: context at least 8192 and memory at most 8 GB. Reply with exactly A, B, or NONE.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "NONE"},
		},
		{
			ID:          "logic-order-v1",
			Title:       "Ordering logic",
			Category:    "reasoning",
			Difficulty:  "medium",
			Description: "Tests a compact symbolic ordering problem.",
			Prompt:      "A finishes before B. C finishes after B. D finishes before A. Which item must finish last? Reply with exactly one letter.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "C"},
		},
		{
			ID:          "sequence-v1",
			Title:       "Simple sequence",
			Category:    "reasoning",
			Difficulty:  "easy",
			Description: "Tests whether the model can infer a simple progression without extra prose.",
			Prompt:      "Complete the sequence and reply with only the next integer: 2, 6, 12, 20, 30, ?",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "42"},
		},
		{
			ID:          "evidence-vs-judgment-v1",
			Title:       "Evidence distinction",
			Category:    "reasoning",
			Difficulty:  "medium",
			Description: "Tests the central project distinction between observed behavior and qualification.",
			Prompt:      "A model returned HTTP 200, valid JSON, finish_reason stop, and a fluent answer. Does that prove the answer is technically correct? Reply exactly YES or NO.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "NO"},
		},
		{
			ID:          "fact-extraction-v1",
			Title:       "Fact extraction",
			Category:    "extraction",
			Difficulty:  "easy",
			Description: "Tests retention of multiple explicit facts.",
			Prompt:      "Passage: The Sparrow service runs on port 7400. Its owner is Maya. The deployment region is us-east-2. Return one short line containing all three facts.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationContainsAll, Contains: []string{"7400", "Maya", "us-east-2"}},
		},
		{
			ID:          "entity-json-v1",
			Title:       "Entity extraction JSON",
			Category:    "extraction",
			Difficulty:  "easy",
			Description: "Tests strict extraction into typed-looking JSON values.",
			Prompt:      "Text: Invoice INV-204 costs $83.50 and is due 2026-09-15. Return only JSON with keys invoice, amount, due. amount must be a number.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationJSONExact, ExpectedJSON: `{"invoice":"INV-204","amount":83.5,"due":"2026-09-15"}`},
		},
		{
			ID:          "classification-v1",
			Title:       "Bounded classification",
			Category:    "extraction",
			Difficulty:  "easy",
			Description: "Tests mapping text into a closed label set.",
			Prompt:      "Classify this support message using exactly one label: BILLING, BUG, FEATURE. Message: 'The app crashes whenever I click Export.' Reply with the label only.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "BUG"},
		},
		{
			ID:          "contradiction-v1",
			Title:       "Contradiction detection",
			Category:    "analysis",
			Difficulty:  "easy",
			Description: "Tests whether the model notices a direct contradiction.",
			Prompt:      "Statement 1: The server is listening on port 8080. Statement 2: No process is listening on port 8080. Can both be true at the same instant under the same observation scope? Reply exactly YES or NO.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "NO"},
		},
		{
			ID:          "source-grounding-v1",
			Title:       "Source grounding discipline",
			Category:    "analysis",
			Difficulty:  "medium",
			Description: "Tests refusal to invent unsupported detail from a supplied mini-source.",
			Prompt:      "Source: 'The test suite passed. Runtime startup took 3.2 seconds.' Question: Which model was used? Reply exactly UNKNOWN if the source does not say.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "UNKNOWN"},
		},
		{
			ID:          "failure-classification-v1",
			Title:       "Failure boundary classification",
			Category:    "analysis",
			Difficulty:  "medium",
			Description: "Tests transport/protocol reasoning.",
			Prompt:      "An HTTP client connects successfully, receives status 200, but the body is malformed JSON and cannot be decoded. Reply with exactly one label: TRANSPORT, HTTP, PROTOCOL, TASK.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "PROTOCOL"},
		},
		{
			ID:          "summary-facts-v1",
			Title:       "Faithful summarization",
			Category:    "writing",
			Difficulty:  "medium",
			Description: "Human-judged concise summary requiring preservation of important facts.",
			Prompt:      "Summarize in at most 45 words: LocalCTL starts llama-server as a separate process, waits for /health to become ready, records the managed PID and model artifact, can inspect /v1/models, performs inference over HTTP, and prefers SIGTERM for graceful shutdown.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
		{
			ID:          "rewrite-concise-v1",
			Title:       "Concise rewrite",
			Category:    "writing",
			Difficulty:  "medium",
			Description: "Human-judged editing task for clarity and compression.",
			Prompt:      "Rewrite this into one clear sentence without changing its meaning: 'The reason that we are collecting the evidence over time is because later on we want to be able to look back at what actually happened instead of just remembering what we thought probably happened.'",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
		{
			ID:          "technical-explanation-v1",
			Title:       "Technical explanation",
			Category:    "writing",
			Difficulty:  "medium",
			Description: "Human-judged explanation task balancing accuracy and accessibility.",
			Prompt:      "Explain in 120 words or fewer why 'process started' is not the same as 'server ready'. Write for a developer who knows programming but is new to process supervision.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
		{
			ID:          "uncertainty-v1",
			Title:       "Uncertainty discipline",
			Category:    "analysis",
			Difficulty:  "medium",
			Description: "Tests whether the model distinguishes observation from speculation.",
			Prompt:      "Observation: one startup took 13.7 seconds and a later startup took 2.8 seconds. We did not measure filesystem cache state. Is it proven that filesystem caching caused the speedup? Reply exactly YES or NO.",
			Baseline:    true,
			Evaluation:  evaluationSpec{Kind: evaluationExact, Expected: "NO"},
		},
		{
			ID:          "planning-tradeoff-v1",
			Title:       "Bounded planning tradeoff",
			Category:    "planning",
			Difficulty:  "hard",
			Description: "Human-judged planning exercise testing prioritization without architecture inflation.",
			Prompt:      "A learner has a working local-model runtime controller but no historical evidence store. Choose the next single implementation slice that maximizes future learning value. State the choice, why it comes first, and one thing explicitly deferred. Maximum 120 words.",
			Baseline:    false,
			Evaluation:  evaluationSpec{Kind: evaluationManual},
		},
	}
}
