package main

import (
	"fmt"
	"io"
)

func runHelp(stdout io.Writer) int {
	fmt.Fprintf(stdout, "LocalCTL %s — local model capability lab\n\n", localctlVersion)
	fmt.Fprintln(stdout, "Start")
	fmt.Fprintln(stdout, "  localctl lab                         show this machine and the learning loop")
	fmt.Fprintln(stdout, "  localctl next                        show what is worth learning next")
	fmt.Fprintln(stdout, "  localctl models                      list installed GGUF models")
	fmt.Fprintln(stdout, "  localctl audition <model>            guided model characterization")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Discover candidates")
	fmt.Fprintln(stdout, "  localctl radar                       scan Hugging Face against this machine and your criteria")
	fmt.Fprintln(stdout, "  localctl radar criteria              inspect or change the discovery criteria")
	fmt.Fprintln(stdout, "  localctl explore                     manage the candidate discovery/audit queue")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Know the territory")
	fmt.Fprintln(stdout, "  localctl capability <model>          derive a current evidence-backed capability map")
	fmt.Fprintln(stdout, "  localctl matrix                      compare installed-model capability evidence")
	fmt.Fprintln(stdout, "  localctl recommend <pack>            find the current evidence leader for a workload")
	fmt.Fprintln(stdout, "  localctl requalify <model>           plan the highest-value evidence refresh")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Compare and learn")
	fmt.Fprintln(stdout, "  localctl headtohead <a> <b>          same-pack controlled comparison")
	fmt.Fprintln(stdout, "  localctl verify <exercise> <model>   repeatability check")
	fmt.Fprintln(stdout, "  localctl missions                    intent-oriented learning paths")
	fmt.Fprintln(stdout, "  localctl packs                       versioned workload packs")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Use your own work")
	fmt.Fprintln(stdout, "  <input> | localctl work <kind> <model>")
	fmt.Fprintln(stdout, "  localctl try <model> <prompt>")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Read the evidence")
	fmt.Fprintln(stdout, "  localctl report <model>              historical characterization")
	fmt.Fprintln(stdout, "  localctl gaps <model>                under-tested areas and next experiment")
	fmt.Fprintln(stdout, "  localctl intelligence list|show      inspect derived capability snapshots")
	fmt.Fprintln(stdout, "  localctl intelligence audit          verify derived claims still resolve to source runs")
	fmt.Fprintln(stdout, "  localctl runs                         recent durable runs")
	fmt.Fprintln(stdout, "  localctl show <run-id>                inspect one run")
	fmt.Fprintln(stdout, "  localctl judge <run-id> ...           attach human judgment")
	fmt.Fprintln(stdout, "  localctl evidence audit               validate stored evidence")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Glass box")
	fmt.Fprintln(stdout, "  localctl runtime status|inspect|start|stop|infer")
	fmt.Fprintln(stdout, "  localctl check")
	fmt.Fprintln(stdout, "  localctl profiles")
	fmt.Fprintln(stdout, "  localctl exercises [category] [--all]")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "External metadata may propose a question. Only local evidence can support a capability claim, and recommendation still grants no execution authority.")
	return 0
}
